## Makefile


latex clinicalcodes
bibtex clinicalcodes
latex clinicalcodes
latex clinicalcodes
dvipdf clinicalcodes

# Pandoc to word for dinosaurs
#pandoc -s -S clinicalcodes.tex -o clinicalcodes.docx --bibliography=clinicalcodes.bib --csl=plos.csl.txt


